# Generated by Django 4.1.3 on 2023-02-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='contenido',
        ),
    ]
