# Generated by Django 4.1.3 on 2023-02-20 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apptienda', '0002_rename_fecha_creacion_categoria_actualizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='actualizado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='creado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
