# Generated by Django 4.1.3 on 2023-02-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptienda', '0003_producto_actualizado_producto_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
