# Generated by Django 4.1.3 on 2023-02-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptienda', '0004_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
